"""create repository files table

Revision ID: 71d234d567cc
Revises: cd2d9e00d289
Create Date: 2026-09-01 14:00:05.752116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d234d567cc'
down_revision: Union[str, Sequence[str], None] = 'cd2d9e00d289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='Cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path', name='uq_repository_files_project_path')
    )
    op.create_index(op.f('ix_repository_files_project_id'), 'repository_files', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_files_project_id'), table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
